### ISSUE TITLE
Found 2 issues with version 1.0.0-beta1

### ISSUE THREAD

**Issue by AlbertDijksma** [ewikner/org.mysensors.homey#19]
Hi Erik,

I’m playing around with your mysensors app for Homey.
I have installed version 1.0.0-beta1. on homey version 1.1.9
The gateway is a raspberry configured as “Ethernet” connection.
I have built some motion sensors which are working perfect.

Now I have found 2 issues when a want to build an actuator:
1>	When I use “present(11, S_BINARY);” it is shown as “S_LICHT”
2>	When I use this little test code there are no nodes shown in homey.

#define MY_DEBUG
#define MY_RADIO_NRF24
#include <MySensors.h>

void setup()
{
}

void presentation()
{
  sendSketchInfo("Relay", "1.0");
  present(11, S_BINARY);
}

void loop()
{
}

void receive(const MyMessage &message)
{
  if (message.type == V_STATUS) {
    Serial.print("Incoming change for sensor:");
    Serial.print(message.sensor);
    Serial.print(", New status: ");
    Serial.println(message.getBool());
  }
}

Homey is only shown nodes who are sending information (values) to Homey.
The work around for the code above is to add this code to the void setup()
void setup()
{
  MyMessage msg(11, V_STATUS);
  send(msg.set(1));
}

Kind regards
Albert

**Comment by ewikner** [comment]
Thanks for reporting the issue.
I can see that mysensors have change presentation S_LIGHT to S_BINARY, I will change this.
Yes, correct that Homey will only show nodes that is sending values.
