### ISSUE TITLE
Units water flow

### ISSUE THREAD

**Issue by AlbertDijksma** [ewikner/org.mysensors.homey#20]
Hi Erik

I have a little issue with my water meter.
The units for the flow is presented as L/h
I think, this must be L/min

I have installed version 1.0.0-beta1

Log:
124282 TSF:MSG:SEND,9-9-0-0,s=2,c=1,t=34,pt=7,l=5,sg=0,ft=0,st=OK:33.16

![2017-03-28 22_45_49- 2 zones devices - homey](https://cloud.githubusercontent.com/assets/25565832/24426846/4991faf6-1409-11e7-814f-85c4df227751.jpg)

Kind regards,
Albert

**Comment by ewikner** [comment]
Hi,
I will create an other capability with unit L/min, becouse some users have L/h and other have L/min.
