### ISSUE TITLE
I’m missing the light_hue, light_saturation and light_temperature in the card

### ISSUE THREAD

**Issue by AlbertDijksma** [ewikner/org.mysensors.homey#22]
Hi Erik,
I want to build rgb led bulbs.
I’m missing the light_hue, light_saturation and light_temperature in the card (the card is empty)
Homey Firmware Versie: 1.2.0
MySensors Version: v0.2.0
Kind regards,
Albert

**Comment by ewikner** [comment]
Hi,
I need more information how you have done to answer this.
Please use the forum on mysensors.

**Comment by AlbertDijksma** [comment]
Hi Erik

I think I was not clear about the problem I have.
Now I have add some screenshots.

When I add a new sensor witch is switching my light witch is able to switch on/off , dim and adjust the hue
The presentation in de windows homey config app mobile app are not correct.
De position of the OnOff slide label in the mobile app is not on the right position.
De label of the Dim slide is missing.
The controls for the light_hue is complete missing.
The controls for the light_saturation, light_temperature and light_mode are also missing in de windows config app and the mobile app.
![homey_config_add_sensors](https://cloud.githubusercontent.com/assets/25565832/25311903/80466b38-280c-11e7-8889-7dc21f285e32.jpg)
![_homey_config_config_on_off_0](https://cloud.githubusercontent.com/assets/25565832/25311905/83c8da34-280c-11e7-8f32-8e16d83e7e8f.jpg)
![homey_config_config_dim_1](https://cloud.githubusercontent.com/assets/25565832/25311906/87911636-280c-11e7-805a-2b5e291e0d3b.jpg)
![homey_config_config_hue_2](https://cloud.githubusercontent.com/assets/25565832/25311909/8c04caaa-280c-11e7-818f-617b1b1f2c24.jpg)
![homey_config_tool](https://cloud.githubusercontent.com/assets/25565832/25311911/945f9ec8-280c-11e7-8e80-4132fb4b9d88.jpg)
![samsunga5](https://cloud.githubusercontent.com/assets/25565832/25311912/967f68fa-280c-11e7-814b-a094f253132b.png)
![samsungtabs2](https://cloud.githubusercontent.com/assets/25565832/25311913/98cbcf90-280c-11e7-85b7-e0d2e3104cb4.png)


Kind regards,
Albert
