### ISSUE TITLE
I think I was not clear about the problem I have

### ISSUE THREAD

**Issue by AlbertDijksma** [ewikner/org.mysensors.homey#23]
Hi Erik

I think I was not clear about the problem I have.
Now I have add some screenshots.

When I add a new sensor which is switching my light which is able to switch on/off , dim and adjust the hue
The presentation in de windows homey config app mobile app are not correct.
De position of the OnOff slide label in the mobile app is not on the right position.
De label of the Dim slide is missing.
The controls for the light_hue is complete missing.
The controls for the light_saturation, light_temperature and light_mode are also missing in de windows config app and the mobile app.
![homey_config_add_sensors](https://cloud.githubusercontent.com/assets/25565832/25311903/80466b38-280c-11e7-8889-7dc21f285e32.jpg)
![_homey_config_config_on_off_0](https://cloud.githubusercontent.com/assets/25565832/25311905/83c8da34-280c-11e7-8f32-8e16d83e7e8f.jpg)
![homey_config_config_dim_1](https://cloud.githubusercontent.com/assets/25565832/25311906/87911636-280c-11e7-805a-2b5e291e0d3b.jpg)
![homey_config_config_hue_2](https://cloud.githubusercontent.com/assets/25565832/25311909/8c04caaa-280c-11e7-818f-617b1b1f2c24.jpg)
![homey_config_tool](https://cloud.githubusercontent.com/assets/25565832/25311911/945f9ec8-280c-11e7-8e80-4132fb4b9d88.jpg)
![samsunga5](https://cloud.githubusercontent.com/assets/25565832/25311912/967f68fa-280c-11e7-814b-a094f253132b.png)
![samsungtabs2](https://cloud.githubusercontent.com/assets/25565832/25311913/98cbcf90-280c-11e7-85b7-e0d2e3104cb4.png)

Kind regards,
Albert

**Comment by ewikner** [comment]
Hi, 
Thanks for write more info about your issue.
As i said before please use forum at mysensors we have our own category for this app. [Here](https://forum.mysensors.org/category/35/homey)
Here you post issues if there is any error with the code and it looks like most of your problems is with Homey and not this app.

/Erik
