### ISSUE TITLE
Could you add value less then greater then card in Homey?

### ISSUE THREAD

**Issue by rhannink** [ewikner/org.mysensors.homey#24]
Hello,

I have some light sensors based on my sensors.

I would like to turn the lights on when the value goes below a certain level.

Could you add an "value is greater then" and a "value is less then" card?

With kind regards and keep the good work......

Remco

**Comment by ewikner** [comment]
Hi,
You can do this with in the flow editor choose when "Value change" and the adding a logic card that is a default card in Homey. The under tags you can drag the sensor you want to use.
Like this:
![skarmavbild 2017-05-11 kl 20 18 28](https://cloud.githubusercontent.com/assets/17088588/25965048/1884fff8-3687-11e7-8d76-7109fe4ed66e.png)

Try it and then get back if you still have some issues.
