### ISSUE TITLE
interface, termostat, energy meter

### ISSUE THREAD

**Issue by Korenets** [ewikner/org.mysensors.homey#28]
I bought Homi for building a smart home based on the plugin mysensors. When adding devices with a large number of sensors it is inconvenient to display the devices in the Homey interface. It is necessary to rewind the slider in a small window. In the interface Homi huge free space, where you can beautifully and informatively display the work of sensors. 
It would be ideal if the sensors were individually in the Homey interface. To be able to distribute the rooms.
https://drive.google.com/file/d/0B1vxUzU0x8vIbDhwTk8xcEltV28/view

 I have one ithernet geteway running on wires, and two on NRF 24, and I can add only 1. 
I tried to use the Mqtt protocol. And all my 40 devices are defined as NODE ID 0 and in one small window of the Homey interface. This is very bad.

It is impossible to correctly add the thermostat, as well as to set the correct readings of water, gas and energy meters

**Comment by ewikner** [comment]
Hi,
I can the the issue you have.
The first version of the app hade each sensor as own device but then the users said it was har do see becouse it was so many devices.
Then in the later version and the current we have one device for each node.
But if you have a lot of sensors on each node i can see the issue.
I know that there has been a lot of changes in Homey so maybe there is an other way to do it today.

But then I need to rewrite the app.
So there is no easy fix for this now, If you can make changed and then send a Pull request to the app.
