### ISSUE TITLE
SDK V2 update?

### ISSUE THREAD

**Issue by Swiftnesses** [ewikner/org.mysensors.homey#32]
Hi Erik,

I hope you're well!

Is there a chance that the app will be updated to SDK V2? The V2.0 Homey update will arrive soon and currently this app will no longer work :(

Cheers.

**Comment by ewikner** [comment]
Hi,

I have sold my Homey so currently I will not update this application to SDK V2

**Comment by Swiftnesses** [comment]
Boo, sorry to see you go! The app was updated by another member, so we're good to go.
